# Generated by Django 3.2.8 on 2021-10-25 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_branch', models.CharField(choices=[('USMC', 'United States Marine Corps'), ('USA', 'United States Army'), ('USN', 'United States Navy'), ('USAF', 'United States Air Force'), ('NG', 'National Guard'), ('USCG', 'United States Coast Guard'), ('RSV', 'Reserves'), ('SF', 'Space Force')], max_length=4)),
                ('purpose', models.TextField()),
                ('member_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunityForums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
