# Generated by Django 3.2.8 on 2021-10-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityforums',
            name='forum_branch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='community.communitybranch'),
        ),
    ]
